version: 1.0.{build}
image: Visual Studio 2024

environment:
  nodejs_version: 14

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

test_script:
  - npm test
